require "rake/extensiontask"
require 'bundler'

PLATFORMS = ["x86_64-linux", "arm-linux", "aarch64-linux", "x86-linux", "x86_64-darwin", "arm64-darwin", "x86-mingw32", "x64-mingw32", "x64-mingw-ucrt"]

spec = Bundler.load_gemspec("rust_ruby_example.gemspec").tap do |s|
  s.platform = Gem::Platform::RUBY
  s.extensions = FileList["ext/**/extconf.rb"]
end

Rake::ExtensionTask.new("rust_ruby_example", spec) do |ext|
  ext.source_pattern = "*.{rs,Cargo.toml}"
  ext.cross_compile = true
  ext.cross_platform = PLATFORMS
end

Gem::PackageTask.new(spec) do |pkg|
end

PLATFORMS.each do |plat|
  task "gem:native:#{plat}" do
    require "rake_compiler_dock"
    ENV["RCD_IMAGE"] = "rbsys/rcd:#{plat}"
    sh "bundle package --all" # Avoid repeated downloads of gems by using gem files from the host.
    RakeCompilerDock.sh <<~EOS, platform: plat
      set -e
      bundle --local 
      rake -T
      rake native:#{plat} gem
    EOS
  end
end
