---
name: Build and push docker images

on:
  - workflow_dispatch

jobs:
  docker_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ruby_target: x86_64-linux
          - ruby_target: aarch64-linux
          - ruby_target: arm-linux
          - ruby_target: x86-linux
          - ruby_target: x86_64-darwin
          - ruby_target: arm64-darwin
          # - ruby_target: x64-mingw-ucrt
          # - ruby_target: x64-mingw32
          # - ruby_target: x86-mingw32
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" 
          bundler-cache: true 

      - name: 🧱 Build container
        env:
          RBSYS_DOCKER: "docker buildx"
          RBSYS_DOCKER_BUILD_EXTRA_ARGS: "--cache-from=type=registry,ref=rbsys/rcd:${{ matrix.platform.ruby_version}}-buildcache --cache-to=type=registry,ref=rbsys/rcd:${{ matrix.platform.ruby_version}}-buildcache,mode=max"
        run: |
          docker buildx create --driver docker-container --use
          rake docker:build:${{ matrix.platform.ruby_target }}